### ISSUE TITLE
Feature: promise API for properties.

### ISSUE THREAD

**Issue by mikeal** [mikeal/gza#3]
```javascript
let init = async (element) => {
  let value = await element.waitFor('propertyName')
}
gza`
${init}
<my-element>
  <span>${ async (settings) => setttings.waitFor('propertyName') }</span>
</my-element>
`
```

This would allow users to effectively block initialization and/or rendering until specific required properties are set.

This is pretty important for cases where complex objects must be set as properties for the an element to function. This opens up the possibility for those properties to be set at any time but still normalize into a linear render path.

**Comment by avoidwork** [comment]
i think this would be fantastic; when used with lazy datum decoration it is very powerful.

**Comment by mikeal** [comment]
This is in, it was implemented in `rza` and the latest dep taken.
